#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# Linux Agentic Tool v2.0 — Installer
# Run on your Linux server:
#   bash <(curl -sL https://YOUR_HOST/install.sh)
# Or locally:
#   bash install.sh
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MIN_PYTHON_MAJOR=3
MIN_PYTHON_MINOR=8

# ── Colours ────────────────────────────────────────────────────────
GREEN="\033[92m"
YELLOW="\033[93m"
RED="\033[91m"
CYAN="\033[96m"
BOLD="\033[1m"
RESET="\033[0m"

ok()   { echo -e "  ${GREEN}✓${RESET} $*"; }
info() { echo -e "  ${CYAN}[i]${RESET} $*"; }
warn() { echo -e "  ${YELLOW}[!]${RESET} $*"; }
die()  { echo -e "  ${RED}[ERR]${RESET} $*"; exit 1; }

echo ""
echo -e "  ${CYAN}${BOLD}┌──────────────────────────────────────────────┐${RESET}"
echo -e "  ${CYAN}${BOLD}│   Linux Agentic Tool v2.0 — Installer         │${RESET}"
echo -e "  ${CYAN}${BOLD}│   AI-Powered Linux Server Management           │${RESET}"
echo -e "  ${CYAN}${BOLD}└──────────────────────────────────────────────┘${RESET}"
echo ""

# ── Check Python 3 ─────────────────────────────────────────────────
if ! command -v python3 &>/dev/null; then
    warn "Python 3 not found. Installing..."
    if command -v apt &>/dev/null; then
        sudo apt-get update -qq && sudo apt-get install -y python3 python3-pip
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y python3 python3-pip
    elif command -v yum &>/dev/null; then
        sudo yum install -y python3 python3-pip
    elif command -v pacman &>/dev/null; then
        sudo pacman -Sy --noconfirm python python-pip
    elif command -v zypper &>/dev/null; then
        sudo zypper install -y python3 python3-pip
    else
        die "Could not install Python 3 automatically. Please install it manually."
    fi
fi

# ── Version check ────────────────────────────────────────────────────
PYTHON_VERSION=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PYTHON_MAJOR=$(python3 -c "import sys; print(sys.version_info.major)")
PYTHON_MINOR=$(python3 -c "import sys; print(sys.version_info.minor)")

if [[ $PYTHON_MAJOR -lt $MIN_PYTHON_MAJOR ]] || \
   [[ $PYTHON_MAJOR -eq $MIN_PYTHON_MAJOR && $PYTHON_MINOR -lt $MIN_PYTHON_MINOR ]]; then
    die "Python ${MIN_PYTHON_MAJOR}.${MIN_PYTHON_MINOR}+ is required. Found: ${PYTHON_VERSION}"
fi

ok "Python ${PYTHON_VERSION} found (required: ${MIN_PYTHON_MAJOR}.${MIN_PYTHON_MINOR}+)"

# ── Ensure pip is available ──────────────────────────────────────────
if ! python3 -m pip --version &>/dev/null; then
    warn "pip not found. Installing..."
    if command -v apt &>/dev/null; then
        sudo apt-get install -y python3-pip
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y python3-pip
    else
        python3 -m ensurepip --upgrade || die "Could not install pip. Install it manually."
    fi
fi

# ── Install Python dependencies ──────────────────────────────────────
info "Installing Python dependencies..."
if ! python3 -m pip install --user -q -r "${REPO_DIR}/requirements.txt" 2>/dev/null; then
    info "Standard pip install failed. Retrying with --break-system-packages..."
    python3 -m pip install --user --break-system-packages -q -r "${REPO_DIR}/requirements.txt" || die "Failed to install dependencies."
fi
ok "Dependencies installed."

# ── Create launcher script ───────────────────────────────────────────
mkdir -p "$HOME/.local/bin"
LAUNCHER="$HOME/.local/bin/linuxagent"

cat > "${LAUNCHER}" << LAUNCHEREOF
#!/usr/bin/env bash
# Linux Agentic Tool launcher — auto-generated by install.sh
exec python3 "${REPO_DIR}/main.py" "\$@"
LAUNCHEREOF

chmod +x "${LAUNCHER}"
ok "Launcher created at ${LAUNCHER}"

# ── Ensure ~/.local/bin is in PATH ──────────────────────────────────
if [[ ":${PATH}:" != *":${HOME}/.local/bin:"* ]]; then
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.bashrc"
    warn "Added ~/.local/bin to PATH in ~/.bashrc"
    warn "Run: source ~/.bashrc   (or open a new terminal)"
    export PATH="$HOME/.local/bin:$PATH"
fi

# ── Verify the tool is importable ───────────────────────────────────
info "Verifying installation..."
if python3 -c "import sys; sys.path.insert(0, '${REPO_DIR}/src'); import config, ai_engine, executor, ui, recipes" 2>&1; then
    ok "All modules import cleanly."
else
    warn "Module import check failed — check the output above for errors."
fi

echo ""
echo -e "  ${GREEN}${BOLD}┌──────────────────────────────────────────────┐${RESET}"
echo -e "  ${GREEN}${BOLD}│   Installation complete!                      │${RESET}"
echo -e "  ${GREEN}${BOLD}│                                               │${RESET}"
echo -e "  ${GREEN}${BOLD}│   Run:  linuxagent                            │${RESET}"
echo -e "  ${GREEN}${BOLD}│   Or:   python3 ${REPO_DIR}/main.py          │${RESET}"
echo -e "  ${GREEN}${BOLD}│                                               │${RESET}"
echo -e "  ${GREEN}${BOLD}│   Tip:  export OPENROUTER_API_KEY=sk-xxx      │${RESET}"
echo -e "  ${GREEN}${BOLD}│         to skip the setup wizard              │${RESET}"
echo -e "  ${GREEN}${BOLD}└──────────────────────────────────────────────┘${RESET}"
echo ""
